### PR TITLE
add VarAC to installer.

### PR DESCRIPTION
**Pull request by SpudGunMan**
version 6.1 when released will support wine and it was tested in this project so I figured only good to give back and include it for everyone!

### CODE REVIEW

**Comment by SpudGunMan** [comment]
https://www.varac-hamradio.com/forum/feature-requests/link-for-current-download

request for static link for download

**Comment by SpudGunMan** [comment]
static download link added

**Comment by SpudGunMan** [comment]
new version won't load on pi-wine anymore, yet due to possibly fixable issues on varac side

**Comment by SpudGunMan** [comment]
the old version works copy provided (and offered for testing) for linux works, I dont remember installing dotnet46 I just used this script. the new release sounds a bit unstable yes. anyway sounds like you have a plan I will leave this here for anyone who wants it. I got the idea from https://github.com/WheezyE/Winelink/issues/27

**Comment by WheezyE** [comment]
Oh yeah looks like I documented the time and system requirements that cause
technical challenges in that thread too (as well as here). Thank you for
your testing with this. I’ll keep an eye on it too

**Comment by SpudGunMan** [comment]
FYI just did a new install and it installed versions all latest as of today.

**Comment by SpudGunMan** [comment]
script works on raspberry but not on X86, stashing this here, as needs additional patch.

from varac forums: 
VarAC issue was the version of Wine that was used. script uses Wine 6.0.3. uninstalled that then installed the newer version listed for Linux Mint 21, which is 7.0.1 now working.

**Comment by WheezyE** [comment]
I'm going over this PR again. Nice job getting a static link to download VarAC from.  That's really helpful!  Also well done with finding the Linux compatibility mode setting and enabling it with `sed`.

I was able to get VarAC to run pretty well on my Linux Mint virtual machine (wine 8.0, `winetricks sound=alsa`), but I noticed that the program has some messy behavior on Wine/Linux.  I'm making a list of feature requests to send to VarAC's author later (issue ticket #63) to try to help VarAC's user experience be a bit smoother on Linux.

VarAC also runs on Pi! (with wine-7.1 - the version in the script). I believe I thought it was crashing because its _normal behavior_ is to throw error messages that it's not finding .ini files and also to not run if invoked from its own directory (I have to invoke it from the user's home directory).

**Comment by WheezyE** [comment]
I think VarAC's been able to run this whole time on Pi, but I didn't realize that until I used your PR which ran VarAC from the user's home directory (via shortcut). I just thought it wasn't stable since VarAC was crashing whenever I ran it from its own folder

**Comment by SpudGunMan** [comment]
Ahh Roger yes that would be worth correcting the path :)

**Comment by WheezyE** [comment]
Thank you for this patch. Now that I know that it does run stably - just with run with quirks that we can overcome for now - I'll merge this

**Pull request merged**
