### PR TITLE
add codename detection to fix distribution fails

### PR DESCRIPTION
**Pull request by SpudGunMan**
suggestion to handle mint and ubuntu differences on install. mint has a package installer dedicated for codename management. tested against 2(2x.x)Mint|Ubuntu with success on all platforms.

### CODE REVIEW

**Comment by SpudGunMan** [comment]
tested on pi4 and mint-vanessa vm appears working. assume the other branches fall in line but.. 

I have two things in this change which I kept as small as possible. First is the codename detection I didnt look at the script to see why exactly but the existing codename isn't working for Vanessa detection. This seems more platform stable overall and might be worth change? you or I can remove that source request if so?

also feel free to just use the idea and meld it in if you have a better idea to rework this entire section 

if you $ cat /etc/lsb-release 
you can see what else is available for OS detection and since your just scripting for Debian should always work.

**Comment by WheezyE** [comment]
Thank you for looking into these platforms. I’ll try testing them out and
see how we might implement them. My coding time to add things a review PR’s
is a bit limited at the moment but I’ll jump back in when I get a chance.

**Comment by SpudGunMan** [comment]
I do think its worth more consideration vs my quick fix // but also of note /etc/lsb-release isn’t available on pi so a mix of detection might be needed still. If they mess up its a mess for the end user in apt keys and its ugly, double check this for sure.

additionally the package `wine-installer` looks interesting and I didnt look past a successful vara install with any testing on new mint

appears working on rpi4, mint-vanessa, focal and jammy

I cant get 22.10 to load on vm so I didnt bother more and automating wine on bionic wasn’t quick

**Comment by SpudGunMan** [comment]
new code in testing on multiple platforms I think is tighter.. since this is the end of the line for OS hunting we have room to just move variables like this

**Comment by WheezyE** [comment]
Thank you for your help and ideas. I’ll try to review these relatively soon
although I don’t have a timeline yet. Would you be able to squash your
commits? (GitHub desktop can help with squashing and pushing)

**Comment by SpudGunMan** [comment]
just a comment as I am using this internally - I find random apt failures due to dependency order issues sometimes randomly. re-running the script a second time hasn't let me down yet.

**Comment by SpudGunMan** [comment]
this also appears to fix a 2023 issue with winehq

**Comment by SpudGunMan** [comment]
Let me know if you want me to resolve conflicts. Easy to discard the lines for AHK

Also, this patch ideally also should remove the old wine key inclusion on pi, I didn't remove it to keep things  flexible, but long term, This needs a little more clean up. 

Also feel free to just dump this (but still it needs fixed) 

As this fork:branch is being used by a few support threads I will wait for any direction to change. 

Welcome back :)

**Comment by WheezyE** [comment]
> Also, this patch ideally also should remove the old wine key inclusion on pi, I didn't remove it to keep things flexible, but long term, This needs a little more clean up.

The wine installs in the Pi (ARM) sections don't use winehq GPG keys (since they just download the packages directly with wget and dpkg them manually). This is because there isn't a 'kosher' way to install i386 wine on arm systems so we have to kind of hack it together like that.
https://github.com/WheezyE/Winelink/blob/0b6f04e125ee1e05050bc281b31347ba8c1a64e6/install_winelink.sh#L69

I think you might be confusing the Pi sections with the x86/x64 raspbian section 
https://github.com/WheezyE/Winelink/blob/0b6f04e125ee1e05050bc281b31347ba8c1a64e6/install_winelink.sh#L160
The x86/x64 sections do deal with GPG keys since I wanted to keep the installation as clean as possible where I could and use the official Wine repo's for non-ARM systems.

**Comment by WheezyE** [comment]
482de08733229145579e81277b10c233c6abc2a5 I'm not super sure what this part is doing, but I think we probably fixed it with the correct key location stuff for the .sources file for ubuntu/debian (#59). Would you mine re-testing the machines that seemed broken using the latest version of the winelink script from today (0b6f04e125ee1e05050bc281b31347ba8c1a64e6 - or later)?

> Welcome back :)

Thank you! :) I really appreciate that :)

**Comment by SpudGunMan** [comment]
I didnt understand the question on the first 482de no highlight of code. yes I think you got it worked out either way.

I will get my test environment reset and tinker with that friday

**Comment by SpudGunMan** [comment]
No news is good news so far it looks like even better compatibility. exciting news! 

I need to give a rest for hosting limits on downloading these same files 100 times a hour ;) 

So far so good will test over weekend as well. 

Do you need any of my fork's or got it all? I will close any and delete branches and fork when dust settles to tidy up.

**Comment by WheezyE** [comment]
I'll close this PR if your testing with the latest Winelink works ok.

**Comment by SpudGunMan** [comment]
I am using the latest yes

**Pull request closed without merging**
